In [46]:
import numpy as np
np.set_printoptions(suppress=True, precision=4)

In [47]:
M = np.array([
    [-7.71006451e-09,  1.21567122e-10,  7.54873722e-06,  3.66057888e-04],
    [-1.34129714e-10, -1.38071418e-08,  8.59443938e-06, -1.06903467e-03],
    [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00,  1.00000000e+00],
    [-1.13959611e-10, -2.10697273e-10, -2.75202689e-06, -1.98398397e-04]])

In [48]:
a = np.array([[1200 * 1000], [600 * 1000], [1000], [1]])

In [49]:
r = np.matmul(M, a)

In [50]:
r[:2] / r[3]

array([[0.3934],
       [0.2862]])

In [51]:
M * 10000000

array([[      -0.0771,        0.0012,       75.4874,     3660.5789],
       [      -0.0013,       -0.1381,       85.9444,   -10690.3467],
       [       0.    ,        0.    ,        0.    , 10000000.    ],
       [      -0.0011,       -0.0021,      -27.5203,    -1983.984 ]])

In [45]:
rgb = np.random.randint(0, 255, size=[5, 5, 3])
rgb

array([[[ 40, 187, 119],
        [ 81, 174, 243],
        [168,  78, 200],
        [116, 186, 183],
        [246,  18,  25]],

       [[107,  61, 188],
        [ 26,  61, 162],
        [247,  21,  69],
        [102,  83,  42],
        [126, 231, 192]],

       [[249, 217, 197],
        [ 51, 221, 160],
        [  6, 144,  35],
        [105,  16,  30],
        [ 73, 246, 121]],

       [[182, 213,  83],
        [130,  51,  44],
        [196,  80, 180],
        [191, 234, 124],
        [225, 209, 116]],

       [[164, 117, 109],
        [104, 163, 208],
        [128, 151, 117],
        [147,  86,  62],
        [179,  25,  32]]])